# To convert a numpy array to a dataframe of given shape

In [1]:
import numpy as np
import pandas as pd
ser = pd.Series(np.random.randint(1, 10, 5))

In [10]:
t1 = np.array([1])
t1

array([1])

In [11]:
t2 = np.array([1,32,5,7,8,9])
t2

array([ 1, 32,  5,  7,  8,  9])

In [12]:
t3 = np.array([[1,2,3,5],
              [5,6,7,8]])
t3

array([[1, 2, 3, 5],
       [5, 6, 7, 8]])

In [13]:
# 3 -dimensional
t4 = np.array([
        [[1,2,3,4,5],
        [6,7,8,9,0]],
    
        [[0,8,7,9,5],
         [6,32,7,9,0]]
])
t4

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9,  0]],

       [[ 0,  8,  7,  9,  5],
        [ 6, 32,  7,  9,  0]]])

In [15]:
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)

(1,)
(6,)
(2, 4)
(2, 2, 5)


In [28]:
#np.random.randn(12).reshape(2,2,3)
np.random.randn(2, 2, 5).reshape(4,5)



array([[-2.07399915, -1.39156423,  0.80820801, -0.59651821, -0.73975251],
       [ 1.08306671,  0.39682985, -1.59762416, -0.48659107, -0.27324743],
       [ 0.2023045 , -0.53806873,  1.75870498, -1.34599961, -0.57010989],
       [ 1.15005095, -1.08216146,  0.59836663, -0.36339201, -1.76122859]])

In [2]:
ser

0     8
1     1
2     4
3     4
4     6
5     4
6     2
7     4
8     7
9     2
10    7
11    6
12    2
13    2
14    7
15    2
16    1
17    1
18    6
19    7
20    3
21    2
22    5
23    2
24    9
25    1
26    4
27    6
28    9
29    9
30    7
31    9
32    2
33    5
34    4
dtype: int32

In [16]:
df = pd.DataFrame(ser.values.reshape(7,5))
print(df)

   0  1  2  3  4
0  8  1  4  4  6
1  4  2  4  7  2
2  7  6  2  2  7
3  2  1  1  6  7
4  3  2  5  2  9
5  1  4  6  9  9
6  7  9  2  5  4


In [3]:
list('abcdefghijklmnopqrstuvwxyz')

['a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [2]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
ser

0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object

In [4]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [3,6,8,20]

ser.take(pos)

3     d
6     g
8     i
20    u
dtype: object

In [5]:
# Input
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

# Output
# Vertical
print(ser1.append(ser2))

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object


In [6]:
# Horizontal
df = pd.concat([ser1, ser2], axis=1)
print(df)

   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


In [14]:
np.arange(20).reshape(20,-1)
#20,1
#1,20
#5,4
#4,5

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [17]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

#df[['a']]
#df.loc[:, ['a']]
#df.iloc[:, [0]]

a
0   0
1   5
2  10
3  15

In [9]:
# Input
df = pd.DataFrame(np.arange(25).reshape(5, -1))

df

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [10]:
df.iloc[::-1, :]

0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

In [21]:
a = np.arange(20).reshape(5,-1)#.resize(4,5)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [25]:
np.resize(a,(1,5))

array([[0, 1, 2, 3, 4]])

In [30]:
np.arange(12).reshape(2,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [34]:
np.arange(12).reshape(2,3,2).swapaxes(1,2)

array([[[ 0,  2,  4],
        [ 1,  3,  5]],

       [[ 6,  8, 10],
        [ 7,  9, 11]]])

In [36]:
np.repeat(10, 10)

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [40]:
a =np.arange(12).reshape(2,3,2)

In [41]:
np.ravel(a)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
np.ravel([[1, 2, 3], [4, 5, 6]])

array([1, 2, 3, 4, 5, 6])

In [46]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
b = np.ones((2, 2)) 
b

array([[1., 1.],
       [1., 1.]])

In [49]:
a = np.eye(2)
print(a)
print("========= New matrics=======")
b = np.ones((2, 2)) * 2
print(b)

[[1. 0.]
 [0. 1.]]
========= New matrics=======
[[2. 2.]
 [2. 2.]]


In [53]:
a.dot(b)

array([[2., 2.],
       [2., 2.]])

In [55]:
a = np.empty(2)
a

array([1., 1.])

In [56]:
a.fill(10)
a

array([10., 10.])

In [31]:
a = [4, 3, 5, 7, 6, 8]
indices = [0, 1, 4]

In [32]:
np.take(a, indices)

array([4, 3, 6])

In [33]:
a = np.array(a)
a[indices]

array([4, 3, 6])

In [29]:
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

In [31]:
df = pd.DataFrame(data)

In [35]:
df['priority'] = df['priority'].replace({'yes':'True','no':'False'})

In [36]:
df['priority']

0     True
1     True
2    False
3     True
4    False
5    False
6    False
7     True
8    False
9    False
Name: priority, dtype: object

In [37]:
df

age animal priority  visits
0  2.5    cat     True       1
1  3.0    cat     True       3
2  0.5  snake    False       2
3  NaN    dog     True       3
4  5.0    dog    False       2
5  2.0    cat    False       3
6  4.5  snake    False       1
7  NaN    cat     True       1
8  7.0    dog    False       2
9  3.0    dog    False       1

In [38]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})

In [40]:
df

A
0   1
1   2
2   2
3   3
4   4
5   5
6   5
7   5
8   6
9   7
10  7

In [42]:
df.groupby(pd.cut(df['A'], np.arange(0, 101, 10))).sum()

A
A            
(0, 10]    47
(10, 20]    0
(20, 30]    0
(30, 40]    0
(40, 50]    0
(50, 60]    0
(60, 70]    0
(70, 80]    0
(80, 90]    0
(90, 100]   0

In [58]:
df = pd.DataFrame(np.arange(20).reshape(5,4))
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [71]:
df.unstack()#.sort_values()[-3:].tolist()

0  0     0
   1     4
   2     8
   3    12
   4    16
1  0     1
   1     5
   2     9
   3    13
   4    17
2  0     2
   1     6
   2    10
   3    14
   4    18
3  0     3
   1     7
   2    11
   3    15
   4    19
dtype: int32

In [ ]:
l = [1,2,34,5,67,6]
l[-5:]