In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(3,)


In [6]:
print(a[0],a[1],a[2])

1 2 3


In [7]:
a[0] = 5
print(a)

[5 2 3]


In [6]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
print(b.shape)

(4, 3)


In [8]:
b.size

12

In [13]:
print(b[0,2])

3


In [14]:
c = np.array([1.3,5.6,9.7])
print(c)

[1.3 5.6 9.7]


In [18]:
zer = np.zeros(10)
zer

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
d = np.zeros((4,3))+5*0.3
print(d)

[[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]


In [24]:
one = np.ones(10)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
e = np.ones((4,3))*8/4
print(e)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [29]:
f = np.full((4,3),3)

print(f)

[[3 3 3]
 [3 3 3]
 [3 3 3]
 [3 3 3]]


In [52]:
dir(np.random)

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_state',
 'shuffle',
 'standard_cauchy',
 'standard_exponential',
 'stand

In [30]:
g1 = np.random.random(10)
g1

array([0.07205617, 0.59427206, 0.82763096, 0.06345184, 0.00451181,
       0.49061333, 0.02109781, 0.67508647, 0.01718782, 0.91419473])

In [33]:
np.arange(14,22,3)

array([14, 17, 20])

In [50]:
np.random.randn(1,3)

array([[ 0.36277738, -0.03933549,  0.27708949]])

In [45]:
np.random.rand(4,5)

array([[0.82211535, 0.57165082, 0.298577  , 0.37422056, 0.13344676],
       [0.40224474, 0.50576928, 0.60585478, 0.65165043, 0.50071758],
       [0.43728818, 0.20978681, 0.08737853, 0.52744003, 0.33387708],
       [0.46941426, 0.71167114, 0.41769518, 0.54883865, 0.98883933]])

In [38]:
np.random.randint(2,10,100)

array([6, 3, 8, 7, 6, 8, 3, 3, 7, 8, 3, 9, 8, 4, 6, 4, 9, 9, 4, 5, 9, 8,
       7, 2, 8, 7, 6, 5, 6, 8, 4, 5, 7, 8, 9, 6, 3, 8, 4, 9, 7, 6, 5, 9,
       6, 7, 7, 6, 6, 5, 8, 2, 2, 9, 9, 3, 5, 5, 5, 6, 5, 9, 7, 4, 4, 2,
       4, 7, 2, 8, 3, 8, 3, 8, 2, 9, 5, 8, 3, 5, 2, 7, 5, 5, 8, 7, 8, 6,
       7, 7, 7, 5, 3, 3, 8, 3, 8, 5, 8, 4])

In [17]:
g = np.random.random((3,3))
print(g)

[[0.77946034 0.84897588 0.0218667 ]
 [0.36691932 0.75448726 0.28407468]
 [0.99959388 0.70009013 0.36813206]]


In [56]:
h = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(h)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
h[1,1] = 500

In [64]:
#k = np.copy(h)
k

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

In [57]:
i= h[:2,:2]
print(i)

print(h[0,1])

i

[[1 2]
 [4 5]]
2


array([[1, 2],
       [4, 5]])

In [67]:
i[0,0] = 100

h[h> 10]

array([100, 500])

In [30]:
j = np.array([[1,2],
            [3,6],
            [9,8]])

print(j)

print(j>2)

print(j[j>3])

[[1 2]
 [3 6]
 [9 8]]
[[False False]
 [ True  True]
 [ True  True]]
[6 9 8]


In [68]:
k = np.array([[1,2],
             [3,4]])
l = np.array([[5,6],
             [7,8]])

print(np.add(k,l)) #print(k + l)
#print(np.subtract(k,l)) #print(k - l)
#print(np.multiply(k,l)) #print( k *l)
#print(np.divide(k,l)) #print(k/l)

[[ 6  8]
 [10 12]]


In [69]:
k

array([[1, 2],
       [3, 4]])

In [37]:
print(np.sum(k))

10


In [38]:
print(np.sum(k,axis = 0))

[4 6]


In [39]:
print(np.sum(k,axis = 1))

[3 7]
